# Generated by Django 4.0.5 on 2022-06-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JfeData1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode_data', models.CharField(max_length=500, unique=True)),
                ('kikaku', models.CharField(blank=True, max_length=100, null=True)),
                ('sunpou', models.CharField(blank=True, max_length=100, null=True)),
                ('nagasa', models.CharField(blank=True, max_length=100, null=True)),
                ('honsuu', models.CharField(blank=True, max_length=100, null=True)),
                ('shitsuryou', models.CharField(blank=True, max_length=100, null=True)),
                ('kouhann', models.CharField(blank=True, max_length=100, null=True)),
                ('kekka_bangou', models.CharField(blank=True, max_length=100, null=True)),
                ('jicqa', models.CharField(blank=True, max_length=100, null=True)),
                ('qa0306011', models.CharField(blank=True, max_length=100, null=True)),
                ('kikaku_hantei', models.IntegerField(blank=True, null=True)),
                ('sunpou_hantei', models.IntegerField(blank=True, null=True)),
                ('nagasa_hantei', models.IntegerField(blank=True, null=True)),
                ('honsuu_hantei', models.IntegerField(blank=True, null=True)),
                ('kessoku_bangou_hantei', models.IntegerField(blank=True, null=True)),
                ('suuchi_keisan_hantei', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jfe_data1',
                'managed': False,
            },
        ),
    ]
