# Generated by Django 4.0.5 on 2022-06-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jfeWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actor',
                'managed': False,
            },
        ),
    ]
