# Generated by Django 4.0.4 on 2022-05-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pushtodatabase',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=255)),
                ('jis_result', models.CharField(max_length=50)),
                ('qr_result', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pushtodatabase',
                'managed': False,
            },
        ),
    ]
